name: lerobot
channels:
  - conda-forge
  - robostack-staging
dependencies:
  - python=3.12
  - pip
  - setuptools>=78.1.1,<81
  - packaging>=24.2,<26
  - msgpack-python>=1.2.1,<2
  - wheel
  - numpy>=2.0,<2.3
  - pandas>=2.2,<3
  - pyarrow>=18,<24
  - pyyaml>=6,<7
  - pillow>=11,<13
  - av>=15,<16
  - ffmpeg>=7,<9
  - opencv>=4.10,<5
  - matplotlib>=3.9,<4
  - ros-humble-ros-base
  - ros-humble-rclpy
  - ros-humble-sensor-msgs
  - ros-humble-std-srvs
  - ros-humble-rcl-interfaces
  - ros-humble-ros2doctor
